version: '3.8'

services:
  safetrade-bot:
    # --- Сборка образа ---
    # Эта секция указывает Docker собрать образ из вашего Dockerfile,
    # а не искать готовый образ в репозитории.
    build:
      context: .
      dockerfile: Dockerfile
    
    # Требование из вашего запроса: принудительно пересобирать образ,
    # даже если он уже существует локально.
    pull_policy: build

    # --- Управление контейнером ---
    # Перезапускать контейнер автоматически, если он упал, но не после ручной остановки.
    # Критически важно для бота, который должен работать 24/7.
    restart: unless-stopped
    
    # Даем контейнеру понятное имя.
    container_name: safetrade-bot-container

    # --- Переменные окружения ---
    # Загружаем все секретные ключи и токены из файла .env.
    # Это безопасный способ управления конфигурацией.
    env_file:
      - .env

    # --- Хранилище (Volumes) ---
    # Создаем постоянное хранилище для логов и кэша.
    # Это гарантирует, что ваши логи и данные не исчезнут при перезапуске контейнера.
    volumes:
      - bot_data:/app/data

    # --- Сеть и порты ---
    # "Пробрасываем" порт 8443 из контейнера на хост-машину.
    # Это необходимо только если вы используете режим Webhook.
    ports:
      - "8443:8443"

# --- Определение именованных томов (volumes) ---
# Docker будет управлять этим томом, что является предпочтительной практикой.
volumes:
  bot_data:
